"""
Surgical regeneration of the checked-in generated datatype modules.

Maintainer aid shipped alongside the #406 fix — not wired into the package, tests,
or CI; intended for the maintainer to adopt during the
planned generator refactor.  Regenerates the ``fhircraft/fhir/resources/datatypes/
{R4,R4B,R5}/{complex,core}`` modules from the packaged StructureDefinitions using
the (fixed) ``CodeGenerator``, so that constraint metadata (``min_length``,
``max_length``, ``ge``, ``le``) reaches the checked-in files.

Guarantees:
- ``primitive-type`` definitions are hard-excluded: the ``primitive/`` modules are
  hand-written and must never be overwritten by generator output.
- Only files that already exist on disk are rewritten; the script never creates
  new files.  Hand-edited modules outside the manifest-derived paths (e.g.
  ``complex/element.py``, ``complex/extension.py``) should additionally be
  reviewed in the diff before committing — verify the exclusion set matches the
  actual hand-edited files.

WARNING — regeneration is NOT idempotent on the current tree:
``CodeGenerator._serialize_model`` skips any field whose ``FieldInfo`` equals the
base class's, and factory models resolve their base class via the checked-in
modules (``get_fhir_type``).  Once a base file gains constraints from one regen
pass, the next pass sees subclass fields as "identical to base" and drops them
from the regenerated subclasses.  A surgical update must therefore start from a
clean tree (all files regenerated in one pass from the pre-update baseline) or
iterate to a fixed point, diffing between passes.
"""

from __future__ import annotations

import re
from pathlib import Path

from fhircraft.fhir.resources.datatypes.registry import TypeRegistry, get_registry
from fhircraft.fhir.resources.factory import FHIRModelFactory
from fhircraft.fhir.resources.generator import CodeGenerator

REPO_ROOT = Path(__file__).resolve().parent.parent
RELEASES = ("R4", "R4B", "R5")
# Never "primitive-type": those modules are hand-written.
GENERATED_KINDS = ("resource", "complex-type")
AUTOGENERATED_HEADER = re.compile(r"^# Code autogenerated by Fhircraft.*\n", re.M)


def _module_file_path(registry: TypeRegistry, url: str) -> Path | None:
    """Resolve the on-disk file for a manifest entry's dotted module path."""
    entry = registry.get_entry(url)
    if entry is None:
        return None
    dotted = registry._build_module_path(entry)
    return REPO_ROOT / Path(*dotted.split(".")).with_suffix(".py")


def _regenerate_release(release: str) -> list[str]:
    registry = get_registry(release)
    factory = FHIRModelFactory(release)
    generator = CodeGenerator()
    written: list[str] = []
    for kind in GENERATED_KINDS:
        for url in sorted(registry.all_urls(kind=kind)):
            file_path = _module_file_path(registry, url)
            if file_path is None or not file_path.exists():
                continue  # never create new files
            model = factory.build(canonical_url=url)
            source_code = generator.generate_resource_model_code(model)
            # Guard: strip the legacy autogenerated header if a template still emits it.
            source_code = AUTOGENERATED_HEADER.sub("", source_code)
            file_path.write_text(source_code)
            relative = file_path.relative_to(REPO_ROOT)
            written.append(str(relative))
            print(f"{release}/{file_path.name}")
    return written


def main() -> None:
    totals: dict[str, int] = {}
    for release in RELEASES:
        totals[release] = len(_regenerate_release(release))
    print("\nSummary:")
    for release, count in totals.items():
        print(f"  {release}: {count} files rewritten")


if __name__ == "__main__":
    main()
